kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pgo-deployer-cr
  labels:
    app.kubernetes.io/name: postgres-operator # {"$kpt-set":"name"}
rules:
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - list
  - create
  - patch
  - delete
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - list
  - get
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - configmaps
  - services
  - persistentvolumeclaims
  verbs:
  - get
  - create
  - delete
  - list
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - get
  - create
  - delete
  - patch
  - list
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - get
  - create
  - delete
  - bind
  - escalate
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
  - list
- apiGroups:
  - crunchydata.com
  resources:
  - pgclusters
  - pgreplicas
  - pgpolicies
  - pgtasks
  verbs:
  - delete
  - list
